name: CD

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: ['ci']
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-react-${{ github.sha }}
      - run: tar -xvf build.tar
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist