name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: |
          yarn install
          yarn playwright install --with-deps
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/yarn.lock') }}